"use strict";

// API contract tests — pin the HTTP response SHAPES that public/app.js consumes.
//
// A contract test drives the REAL route (in-process, against the exported `app`)
// and asserts field names + types + nesting — never concrete values. Values
// change every time data/*.json is regenerated by Suggested Updates; the shape is
// what the frontend depends on and what an optimisation must preserve.
//
// This file is the safety net for the "optimise without breaking" work: it proves
// "behaviour unchanged" so dedupe / dead-code / module-split steps can't silently
// rename a field or drop a key that the frontend reads.
//
// Mechanics: server.js exports `app` and guards `listen()` behind
// `require.main === module`, so `require("../server")` never binds a port. We
// drive routes with Node's built-in http + fetch against 127.0.0.1:0 — no new
// dependencies, no external socket. The reference for every assertion below is
// docs/api-contract.md.

process.env.SCAN_MODEL_MIN_GAP_MS = "50";      // keep any scan pacing fast
process.env.TAVILY_API_KEY = "contract-test-key"; // enable /api/search success path

const { test, before, after } = require("node:test");
const assert = require("node:assert");
const http = require("http");

const srv = require("../server");
const app = srv.app;
const realFetch = globalThis.fetch; // saved before any stubbing below

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------
const isStr = (v) => typeof v === "string";
const isNum = (v) => typeof v === "number" && Number.isFinite(v);
const isBool = (v) => typeof v === "boolean";
const isObj = (v) => v !== null && typeof v === "object" && !Array.isArray(v);
const isArr = Array.isArray;

const NEWS_SOURCES = ["Google News RSS", "Bing News RSS", "Cached"];

function startServer() {
  return new Promise((resolve) => {
    const s = http.createServer(app);
    s.listen(0, "127.0.0.1", () => resolve(s));
  });
}
function closeServer(server) {
  return new Promise((resolve) => server.close(resolve));
}

// Requests use `realFetch` (not globalThis.fetch) so stubbing globalThis.fetch in
// the network-route tests never breaks the harness's own HTTP call.
async function request(server, method, path, body) {
  const port = server.address().port;
  const opts = { method, headers: { accept: "application/json" } };
  if (body !== undefined) {
    opts.headers["content-type"] = "application/json";
    opts.body = JSON.stringify(body);
  }
  const res = await realFetch(`http://127.0.0.1:${port}${path}`, opts);
  const text = await res.text();
  let json = null;
  try { json = JSON.parse(text); } catch { /* non-JSON body */ }
  return { status: res.status, contentType: res.headers.get("content-type") || "", body: json, text };
}

function stubFetch(handler) {
  const original = globalThis.fetch;
  globalThis.fetch = handler;
  return () => { globalThis.fetch = original; };
}

// Shared news envelope (docs/api-contract.md §2 "GET /api/news").
function assertNewsEnvelope(body) {
  assert.strictEqual(body.success, true);
  assert.ok(isNum(body.count), "count must be a number");
  assert.ok(isArr(body.articles), "articles must be an array");
  assert.ok(body.articles.length > 0, "articles must be non-empty");
  assert.ok(isArr(body.topics), "topics must be an array");
  assert.ok(isArr(body.monitoredCompetitors), "monitoredCompetitors must be an array");
  for (const c of body.monitoredCompetitors) {
    assert.ok(isStr(c.id), "competitor.id must be a string");
    assert.ok(isStr(c.name), "competitor.name must be a string");
    assert.ok(isBool(c.custom), "competitor.custom must be a boolean");
  }
  assert.ok(isStr(body.searchedAt), "searchedAt must be a string");
  assert.ok(isBool(body.live), "live must be a boolean");
  assert.ok(isBool(body.cached), "cached must be a boolean");
  assert.strictEqual(body.cached, !body.live, "cached must be the inverse of live");
  assert.ok(isStr(body.source) && NEWS_SOURCES.includes(body.source),
    `source must be one of ${NEWS_SOURCES.join(" | ")}`);
}

// Shared article element shape (docs/api-contract.md §3).
function assertArticleShape(a) {
  assert.ok(isStr(a.title) && a.title.length > 0, "article.title must be a non-empty string");
  assert.ok(isStr(a.url) && /^https?:\/\//.test(a.url), "article.url must be an http(s) string");
  assert.ok(isStr(a.sourceName), "article.sourceName must be a string");
  assert.ok(a.publishedAt === null || isStr(a.publishedAt),
    "article.publishedAt must be a string or null");
}

let server;
before(async () => { server = await startServer(); });
after(async () => { if (server) await closeServer(server); });

// ---------------------------------------------------------------------------
// 1. Deterministic read-only GET routes (docs §1)
// ---------------------------------------------------------------------------
test("GET /healthz returns the liveness envelope", async () => {
  const { status, contentType, body } = await request(server, "GET", "/healthz");
  assert.strictEqual(status, 200);
  assert.ok(/application\/json/.test(contentType), "must be JSON");
  assert.strictEqual(body.ok, true);
  assert.ok(isNum(body.uptimeSeconds));
  assert.ok(isBool(body.scanning));
  assert.ok(isObj(body.scanBudget) && isNum(body.scanBudget.used) && isNum(body.scanBudget.limit));
  assert.ok(isObj(body.resolver));
  // Deployment diagnostic fields (added so live probes can confirm the
  // running SHA + news-seed load without reading the Render dashboard).
  assert.ok(isStr(body.commit) && body.commit.length > 0, "commit must be a non-empty string");
  assert.ok(isNum(body.newsSeedArticles), "newsSeedArticles must be a number");
  // Search-chain diagnostics: makes a degraded/circuit-broken search visible to a
  // live probe instead of it only showing up as empty result sets.
  assert.ok(isObj(body.search), "search diagnostics must be an object");
  assert.ok(isArr(body.search.chain) && body.search.chain.length > 0, "search.chain must be non-empty");
  assert.ok(isArr(body.search.providers), "search.providers must be an array");
  for (const p of body.search.providers) {
    assert.ok(isStr(p.name), "provider.name must be a string");
    assert.ok(isBool(p.configured), "provider.configured must be a boolean");
    assert.ok(isBool(p.circuitOpen), "provider.circuitOpen must be a boolean");
  }
  assert.ok(body.search.active === null || isStr(body.search.active),
    "search.active must be a provider name or null");
});

test("GET /api/status returns provider strings", async () => {
  const { status, body } = await request(server, "GET", "/api/status");
  assert.strictEqual(status, 200);
  assert.ok(isStr(body.mode));
  assert.ok(isStr(body.searchProvider));
  assert.ok(isStr(body.scrapeProvider));
});

test("GET /api/knowledge returns the knowledge envelope", async () => {
  const { status, body } = await request(server, "GET", "/api/knowledge");
  assert.strictEqual(status, 200);
  assert.strictEqual(body.success, true);
  assert.ok(isObj(body.data));
  assert.ok(isArr(body.data.sourceDocuments));
  for (const doc of body.data.sourceDocuments) {
    assert.ok(isStr(doc.title), "sourceDocument.title must be a string");
    assert.ok(isStr(doc.file), "sourceDocument.file must be a string");
  }
  assert.ok(isObj(body.data.categories));
  for (const cat of Object.values(body.data.categories)) {
    assert.ok(isStr(cat.label), "category.label must be a string");
    assert.ok(isArr(cat.subsections), "category.subsections must be an array");
  }
});

test("GET /api/network returns the network envelope", async () => {
  const { status, body } = await request(server, "GET", "/api/network");
  assert.strictEqual(status, 200);
  assert.strictEqual(body.success, true);
  assert.ok(isObj(body.data.center));
  assert.ok(isArr(body.data.competitors));
  assert.ok(isObj(body.data.sectorColors));
});

test("GET /api/risks returns the risk envelope", async () => {
  const { status, body } = await request(server, "GET", "/api/risks");
  assert.strictEqual(status, 200);
  assert.strictEqual(body.success, true);
  assert.ok(isObj(body.data.categories));
  assert.ok(isObj(body.data.companyRiskSummaries));
});

test("GET /api/tencent-products returns the product envelope", async () => {
  const { status, body } = await request(server, "GET", "/api/tencent-products");
  assert.strictEqual(status, 200);
  assert.strictEqual(body.success, true);
  assert.ok(isObj(body.data.center));
  assert.ok(isArr(body.data.sectors));
  assert.ok(isArr(body.data.products));
});

test("GET /api/current-use-cases returns the use-case envelope", async () => {
  const { status, body } = await request(server, "GET", "/api/current-use-cases");
  assert.strictEqual(status, 200);
  assert.strictEqual(body.success, true);
  assert.ok(isStr(body.data.title));
  assert.ok(isArr(body.data.patterns));
  assert.ok(isArr(body.data.games));
});

test("GET /api/gaming-trends returns the trends envelope", async () => {
  const { status, body } = await request(server, "GET", "/api/gaming-trends");
  assert.strictEqual(status, 200);
  assert.strictEqual(body.success, true);
  assert.ok(isArr(body.data.trends));
  assert.ok(isObj(body.data.ecosystemContext));
  assert.ok(isObj(body.data.patentLandscape));
  assert.ok(isObj(body.data.currentUseEvidence));
});

test("GET /api/regulatory-timeline returns the timeline envelope", async () => {
  const { status, body } = await request(server, "GET", "/api/regulatory-timeline");
  assert.strictEqual(status, 200);
  assert.strictEqual(body.success, true);
  assert.ok(isStr(body.data.title));
  assert.ok(isArr(body.data.events));
});

test("GET /api/company-locations returns the locations envelope", async () => {
  const { status, body } = await request(server, "GET", "/api/company-locations");
  assert.strictEqual(status, 200);
  assert.strictEqual(body.success, true);
  assert.ok(isObj(body.data.regions));
  assert.ok(isArr(body.data.companies));
});

test("GET /api/regulatory-status returns the monitoring envelope", async () => {
  const { status, body } = await request(server, "GET", "/api/regulatory-status");
  assert.strictEqual(status, 200);
  assert.strictEqual(body.success, true);
  assert.ok(isBool(body.monitoring));
  assert.ok(isBool(body.scanning));
  assert.ok(isNum(body.pendingCount));
  assert.ok(isObj(body.counts));
  assert.ok(isObj(body.model));
});

test("GET /api/proposed-changes returns the pending envelope", async () => {
  const { status, body } = await request(server, "GET", "/api/proposed-changes");
  assert.strictEqual(status, 200);
  assert.strictEqual(body.success, true);
  assert.ok(isArr(body.pending));
  assert.ok(isNum(body.pendingCount));
  assert.strictEqual(body.pendingCount, body.pending.length);
  for (const item of body.pending) {
    assert.ok(isStr(item.id));
    assert.ok(isStr(item.title));
    assert.ok(isStr(item.url));
    assert.strictEqual(item.status, "pending");
  }
});

test("GET /api/news/custom-competitors returns the custom competitor array", async () => {
  const { status, body } = await request(server, "GET", "/api/news/custom-competitors");
  assert.strictEqual(status, 200);
  assert.ok(isArr(body.customCompetitors));
  for (const c of body.customCompetitors) {
    assert.ok(isStr(c.id));
    assert.ok(isStr(c.name));
    assert.strictEqual(c.custom, true);
  }
});

// ---------------------------------------------------------------------------
// 2. Network routes (docs §2) — structural only, fetch stubbed for determinism
// ---------------------------------------------------------------------------
test("GET /api/news/subhead requires an http(s) url (400)", async () => {
  const { status, body } = await request(server, "GET", "/api/news/subhead");
  assert.strictEqual(status, 400);
  assert.ok(isStr(body.error));
});

test("GET /api/news/subhead returns 404 when no subhead is found", async () => {
  const restore = stubFetch(async () => { throw new Error("network down"); });
  try {
    const { status, body } = await request(
      server, "GET", "/api/news/subhead?url=https%3A%2F%2Fexample.com%2Fx&title=Test");
    assert.strictEqual(status, 404);
    assert.ok(isStr(body.error));
  } finally { restore(); }
});

test("POST /api/search requires a query (400)", async () => {
  const { status, body } = await request(server, "POST", "/api/search", {});
  assert.strictEqual(status, 400);
  assert.strictEqual(body.error, "Query is required");
});

test("POST /api/search returns the search envelope (success)", async () => {
  const restore = stubFetch(async (url) => {
    if (String(url).includes("api.tavily.com")) {
      return {
        ok: true, status: 200,
        json: async () => ({ results: [{ title: "A result", url: "https://example.com/r", content: "content body" }] }),
      };
    }
    throw new Error("network down");
  });
  try {
    const { status, body } = await request(server, "POST", "/api/search", { query: "AI regulation", limit: 3 });
    assert.strictEqual(status, 200);
    assert.strictEqual(body.success, true);
    assert.ok(isArr(body.data));
    assert.ok(isNum(body.total));
    assert.strictEqual(body.total, body.data.length, "total must equal data.length");
    for (const r of body.data) {
      assert.ok(isStr(r.title));
      assert.ok(isStr(r.url));
    }
  } finally { restore(); }
});

test("POST /api/search caches repeated identical queries (Step 2c Fix #2)", async () => {
  let tavilyCalls = 0;
  const restore = stubFetch(async (url) => {
    if (String(url).includes("api.tavily.com")) {
      tavilyCalls += 1;
      return {
        ok: true, status: 200,
        json: async () => ({ results: [{ title: "Cached result", url: "https://example.com/c", content: "body" }] }),
      };
    }
    throw new Error("network down");
  });
  try {
    // Unique query string so it cannot collide with the other search test's cache entry.
    const q = "Step2c-unique-search-query-xyz";
    const first = await request(server, "POST", "/api/search", { query: q, limit: 3 });
    assert.strictEqual(first.status, 200);
    assert.strictEqual(first.body.cached, false, "first call fetches live");
    const second = await request(server, "POST", "/api/search", { query: q, limit: 3 });
    assert.strictEqual(second.status, 200);
    assert.strictEqual(second.body.cached, true, "repeat within TTL served from cache");
    assert.strictEqual(tavilyCalls, 1, "Tavily hit once, not twice");
    assert.strictEqual(second.body.total, first.body.total, "same envelope on cache hit");
  } finally {
    restore();
  }
});

test("POST /api/search reports WHICH provider answered", async () => {
  const restore = stubFetch(async (url) => {
    if (String(url).includes("api.tavily.com")) {
      return {
        ok: true, status: 200,
        json: async () => ({ results: [{ title: "P", url: "https://example.com/p", content: "body" }] }),
      };
    }
    throw new Error("network down");
  });
  try {
    const { body } = await request(server, "POST", "/api/search",
      { query: "provider-field-unique-query", limit: 3 });
    assert.strictEqual(body.provider, "tavily", "provider names the leg that answered");
  } finally { restore(); }
});

// The whole point of the chain: a dead primary must DEGRADE, not 500. Drives the
// real route with Tavily failing and only the keyless Jina leg answering.
test("POST /api/search falls back to the keyless jina leg when Tavily fails", async () => {
  srv.searchProvider.resetBreakers();
  const jinaMarkdown = [
    "## Result 1",
    "[Publisher Story](https://publisher.example.com/story)",
    "Real lead paragraph from the publisher.",
  ].join("\n");
  let jinaHits = 0;
  const restore = stubFetch(async (url) => {
    const u = String(url);
    if (u.includes("api.tavily.com")) throw new Error("tavily quota exhausted");
    if (u.includes("s.jina.ai")) {
      jinaHits += 1;
      return { ok: true, status: 200, text: async () => jinaMarkdown };
    }
    throw new Error("network down");
  });
  try {
    const { status, body } = await request(server, "POST", "/api/search",
      { query: "tavily-fallback-unique-query", limit: 3 });
    assert.strictEqual(status, 200, "a dead primary must not 500 the request");
    assert.strictEqual(body.success, true);
    assert.strictEqual(body.provider, "jina", "the keyless leg answered");
    assert.ok(isArr(body.data) && body.data.length > 0, "results still returned");
    assert.strictEqual(body.data[0].url, "https://publisher.example.com/story");
    assert.strictEqual(jinaHits, 1);
  } finally {
    restore();
    srv.searchProvider.resetBreakers(); // don't leak breaker state into later tests
  }
});

test("POST /api/search 500s with a combined reason only when EVERY provider fails", async () => {
  srv.searchProvider.resetBreakers();
  const restore = stubFetch(async () => { throw new Error("total network outage"); });
  try {
    const { status, body } = await request(server, "POST", "/api/search",
      { query: "all-providers-down-unique-query", limit: 3 });
    assert.strictEqual(status, 500);
    assert.ok(isStr(body.error));
    assert.match(body.error, /Web search unavailable/);
  } finally {
    restore();
    srv.searchProvider.resetBreakers();
  }
});

// A minimal valid Google News RSS feed so the LIVE path is exercised without any
// network. Two items: one with a pubDate (-> ISO string) and one without
// (-> null), pinning both branches of the publishedAt sentinel.
function googleNewsRss(items) {
  const body = items.map((it) => `
    <item>
      <title>${it.title}</title>
      <link>${it.url}</link>
      <description>${it.desc || ""}</description>${it.pubDate ? `\n      <pubDate>${it.pubDate}</pubDate>` : ""}
      <source url="https://example.com">${it.source}</source>
    </item>`).join("");
  return `<?xml version="1.0"?><rss version="2.0"><channel><title>Google News</title>${body}</channel></rss>`;
}

// Bing-shaped RSS fixture (namespaced <News:Source>, apiclick.aspx redirector
// links) for the Track 1 race / Bing-fallback test.
function bingNewsRss(items) {
  const body = items.map((it) => `
    <item>
      <title>${it.title}</title>
      <link>https://www.bing.com/news/apiclick.aspx?url=${encodeURIComponent(it.url)}</link>
      <description>${it.desc || ""}</description>${it.pubDate ? `\n      <pubDate>${it.pubDate}</pubDate>` : ""}
      <News:Source>${it.source}</News:Source>
    </item>`).join("");
  return `<?xml version="1.0"?><rss version="2.0" xmlns:News="http://schemas.microsoft.com/news/2006/News"><channel><title>Bing News</title>${body}</channel></rss>`;
}

// NOTE: /api/news fire-and-forgets `enrichTopArticles`, which used to leak one
// 15s timer per enriched article (an un-cleared `Promise.race` timeout). That
// leak is FIXED — `withTimeout` now clears the timer when the race settles — so
// these tests no longer hold the process open after the suite. The tests below
// only pin response shape; they are unaffected by the fix.
test("GET /api/news serves the prewarmed seed on first hit (no blocking fan-out)", async () => {
  // Every fetch fails — so any non-empty response MUST come from the in-memory
  // pre-warm (Track 1.1), not a live fan-out. A `recent` searchedAt proves it
  // came from the in-memory entry (backdated ~65s at boot), NOT the on-disk seed
  // via getNewsFallback (which would carry the old file timestamp).
  const restore = stubFetch(async () => { throw new Error("network down"); });
  try {
    const { status, body } = await request(server, "GET", "/api/news");
    assert.strictEqual(status, 200);
    assertNewsEnvelope(body);
    assert.strictEqual(body.cached, true, "prewarmed entry is served as cached");
    const ageMs = Date.now() - Date.parse(body.searchedAt);
    assert.ok(ageMs >= 0 && ageMs < 10 * 60 * 1000, "served from recent in-memory pre-warm");
    assert.ok(body.articles.length > 0, "seed articles present without a live fetch");
  } finally {
    restore();
  }
});

test("GET /api/news serves the prewarmed seed even after long uptime (regression for serve-TTL expiry)", async () => {
  // The live-verified bug: a deploy that sits idle (Render spin-up, health
  // checks, or a slow first visitor) for >~55s would age the backdated seed
  // past NEWS_SERVE_TTL_MS, expiry it, and fall through to a live fan-out. The
  // seed flag must keep it serveable on the first hit regardless of uptime.
  const realNow = Date.now;
  Date.now = () => realNow() + 20 * 60 * 1000; // pretend 20 min have elapsed
  const restore = stubFetch(async () => { throw new Error("network down"); });
  try {
    const { status, body } = await request(server, "GET", "/api/news");
    assert.strictEqual(status, 200);
    assertNewsEnvelope(body);
    assert.strictEqual(body.cached, true, "seed still served as cached after long uptime");
    assert.strictEqual(body.source, "Bing News RSS", "served from in-memory seed, not a live fetch");
    assert.ok(body.articles.length > 0, "seed articles present");
  } finally {
    Date.now = realNow;
    restore();
  }
});

test("GET /api/news returns the news envelope (cached fallback)", async () => {
  const restore = stubFetch(async () => { throw new Error("network down"); });
  try {
    const { status, body } = await request(server, "GET", "/api/news");
    assert.strictEqual(status, 200);
    assertNewsEnvelope(body);
    assert.strictEqual(body.live, false);
    assert.strictEqual(body.cached, true);
    for (const a of body.articles) assertArticleShape(a);
  } finally {
    restore();
  }
});

test("GET /api/news returns the news envelope (live Google RSS)", async () => {
  const rss = googleNewsRss([
    { title: "EU AI Act final vote", url: "https://example.com/ai-act-1", desc: "Lawmakers approve the act.", pubDate: "Mon, 18 Aug 2026 12:00:00 GMT", source: "Example News" },
    { title: "AI in game development", url: "https://example.com/ai-gaming-2", desc: "Studios adopt AI tooling.", pubDate: null, source: "Example Tech" },
  ]);
  const restore = stubFetch(async (url) => {
    if (String(url).includes("news.google.com")) {
      return {
        ok: true, status: 200, url: String(url),
        headers: { get: (h) => (h.toLowerCase() === "content-type" ? "application/rss+xml" : null) },
        text: async () => rss,
      };
    }
    throw new Error("network down");
  });
  try {
    // ?refresh bypasses the serve-cache (incl. the boot pre-warm) so this test
    // exercises the live Google path directly.
    const { status, body } = await request(server, "GET", "/api/news?refresh=1");
    assert.strictEqual(status, 200);
    assertNewsEnvelope(body);
    assert.strictEqual(body.live, true);
    assert.strictEqual(body.cached, false);
    assert.strictEqual(body.source, "Google News RSS");
    // Both publishedAt branches pinned: one string, one null.
    assert.ok(body.articles.some((a) => isStr(a.publishedAt)), "one article has a date");
    assert.ok(body.articles.some((a) => a.publishedAt === null), "one article has a null date");
    for (const a of body.articles) assertArticleShape(a);
  } finally {
    restore();
  }
});

// --- Step 2c: serve-from-cache + ?refresh bypass ---------------------------------

// Benign response for non-RSS URLs (Tavily / article-host enrichment fetches)
// so the fire-and-forget subhead warming never throws. Only news.google.com
// fetches count toward `newsFetches`, isolating the fan-out from enrichment.
function benignNonNews() {
  return {
    ok: true, status: 200, url: "https://example.com/x",
    headers: { get: () => "text/html" },
    text: async () => "<html><head><meta property=\"og:description\" content=\"lead\"></head><body>lead</body></html>",
  };
}

test("GET /api/news serves from cache on repeat (no extra live fan-out)", async () => {
  let newsFetches = 0;
  const restore = stubFetch(async (url) => {
    if (String(url).includes("news.google.com")) {
      newsFetches++;
      return {
        ok: true, status: 200, url: String(url),
        headers: { get: (h) => (h.toLowerCase() === "content-type" ? "application/rss+xml" : null) },
        text: async () => googleNewsRss([
          { title: "Cacheable article", url: "https://example.com/cache-1", desc: "Cache me.", pubDate: "Mon, 18 Aug 2026 12:00:00 GMT", source: "Example News" },
        ]),
      };
    }
    return benignNonNews();
  });
  try {
    // Force a live fetch first to populate the cache with known data.
    const r1 = await request(server, "GET", "/api/news?refresh=1");
    assert.strictEqual(r1.status, 200);
    assertNewsEnvelope(r1.body);
    const afterPopulate = newsFetches;
    assert.ok(afterPopulate >= 1, "refresh must trigger a live fan-out");
    // A plain call must now serve from cache without another news fan-out.
    const r2 = await request(server, "GET", "/api/news");
    assert.strictEqual(r2.status, 200);
    assertNewsEnvelope(r2.body);
    assert.strictEqual(newsFetches, afterPopulate, "repeat /api/news should serve from cache");
  } finally {
    restore();
  }
});

test("GET /api/news?refresh forces a fresh fan-out each time", async () => {
  let newsFetches = 0;
  const restore = stubFetch(async (url) => {
    if (String(url).includes("news.google.com")) {
      newsFetches++;
      return {
        ok: true, status: 200, url: String(url),
        headers: { get: (h) => (h.toLowerCase() === "content-type" ? "application/rss+xml" : null) },
        text: async () => googleNewsRss([
          { title: "Refreshable article", url: "https://example.com/refresh-1", desc: "Fresh.", pubDate: "Mon, 18 Aug 2026 12:00:00 GMT", source: "Example News" },
        ]),
      };
    }
    return benignNonNews();
  });
  try {
    const r1 = await request(server, "GET", "/api/news?refresh=1");
    assert.strictEqual(r1.status, 200);
    const after1 = newsFetches;
    const r2 = await request(server, "GET", "/api/news?refresh=2");
    assert.strictEqual(r2.status, 200);
    // Each ?refresh runs a full live fan-out; the serve-cache is bypassed, so
    // the total is exactly two fan-outs (not one + a cached serve).
    assert.strictEqual(newsFetches, after1 * 2, "each ?refresh forces a fresh fan-out (no serve-cache)");
  } finally {
    restore();
  }
});

test("GET /api/news falls back to Bing when Google returns empty (Track 1 race)", async () => {
  // Force a Google block (empty feed) and a working Bing feed. With ?refresh the
  // serve-cache is bypassed so the live fan-out runs; both fan-outs race and the
  // empty Google result yields to Bing. Unwrapped publisher URLs prove Bing
  // parsing + the apiclick.aspx unwrap both work.
  const restore = stubFetch(async (url) => {
    if (String(url).includes("news.google.com")) {
      return {
        ok: true, status: 200, url: String(url),
        headers: { get: (h) => (h.toLowerCase() === "content-type" ? "application/rss+xml" : null) },
        text: async () => googleNewsRss([]),
      };
    }
    if (String(url).includes("bing.com")) {
      return {
        ok: true, status: 200, url: String(url),
        headers: { get: (h) => (h.toLowerCase() === "content-type" ? "application/rss+xml" : null) },
        text: async () => bingNewsRss([
          { title: "Bing-sourced AI gaming story", url: "https://example.com/bing-1", desc: "From Bing.", pubDate: "Mon, 18 Aug 2026 12:00:00 GMT", source: "Example News" },
        ]),
      };
    }
    return benignNonNews();
  });
  try {
    const { status, body } = await request(server, "GET", "/api/news?refresh=1");
    assert.strictEqual(status, 200);
    assertNewsEnvelope(body);
    assert.strictEqual(body.source, "Bing News RSS", "Bing fallback used when Google empty");
    assert.ok(body.articles.length > 0, "Bing articles present");
    assert.ok(body.articles.every((a) => !String(a.url).includes("bing.com/news/apiclick")),
      "Bing redirector links are unwrapped to direct publisher URLs");
    for (const a of body.articles) assertArticleShape(a);
  } finally {
    restore();
  }
});

// Thread B — SSE live-update stream. Asserts the endpoint opens a proper
// text/event-stream and pushes at least one frame, then disconnects cleanly so
// the test harness doesn't hang or leak an open socket.
test("GET /api/news/stream opens an SSE stream (text/event-stream)", async () => {
  const port = server.address().port;
  const controller = new AbortController();
  const res = await realFetch(`http://127.0.0.1:${port}/api/news/stream`, {
    headers: { accept: "text/event-stream" },
    signal: controller.signal,
  });
  try {
    assert.strictEqual(res.status, 200, "SSE endpoint must return 200");
    assert.match(res.headers.get("content-type") || "", /text\/event-stream/,
      "content-type must be text/event-stream");
    // Read until we receive at least one frame (server writes ": connected" on open).
    const reader = res.body.getReader();
    const deadline = Date.now() + 5000;
    let received = "";
    while (Date.now() < deadline) {
      const { value, done } = await reader.read();
      if (done) break;
      received += Buffer.from(value).toString("utf8");
      if (received.includes("\n\n")) break;
    }
    assert.ok(received.length > 0, "expected at least one SSE frame from the stream");
  } finally {
    controller.abort();
    // Let the server's req 'close' cleanup run so the socket is gone before the
    // after() hook closes the server.
    await new Promise((r) => setTimeout(r, 50));
  }
});
